/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class eu_powet_groundcopter_MavlinkNative */

#ifndef _Included_eu_powet_groundcopter_MavlinkNative
#define _Included_eu_powet_groundcopter_MavlinkNative
#ifdef __cplusplus
extern "C" {
#endif
#undef eu_powet_groundcopter_MavlinkNative_serialVersionUID
#define eu_powet_groundcopter_MavlinkNative_serialVersionUID 5516075349620653480LL
#undef eu_powet_groundcopter_MavlinkNative_serialVersionUID
#define eu_powet_groundcopter_MavlinkNative_serialVersionUID 1LL
/*
 * Class:     eu_powet_groundcopter_MavlinkNative
 * Method:    registerCallbacks
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_eu_powet_groundcopter_MavlinkNative_registerCallbacks
  (JNIEnv *, jobject);

/*
 * Class:     eu_powet_groundcopter_MavlinkNative
 * Method:    forward
 * Signature: (I[B)V
 */
JNIEXPORT void JNICALL Java_eu_powet_groundcopter_MavlinkNative_forward
  (JNIEnv *, jobject, jint, jbyteArray);

/*
 * Class:     eu_powet_groundcopter_MavlinkNative
 * Method:    createMessage
 * Signature: (Lcom/mavlink/messages/IMAVLinkMessage;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_eu_powet_groundcopter_MavlinkNative_createMessage
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
