package com.mavlink.messages.ardupilotmega;

import com.mavlink.messages.IMAVLinkMessage;
/**
 * Class msg_radio
 * Status generated by radio
 **/
public class msg_radio extends IMAVLinkMessage {
  public static final int MAVLINK_MSG_ID_RADIO = 166;
  private static final long serialVersionUID = MAVLINK_MSG_ID_RADIO;
  public msg_radio() {
    messageType = MAVLINK_MSG_ID_RADIO;

}

  /**
   * receive errors
   */
  public int rxerrors;
  /**
   * count of error corrected packets
   */
  public int fixed;
  /**
   * local signal strength
   */
  public int rssi;
  /**
   * remote signal strength
   */
  public int remrssi;
  /**
   * how full the tx buffer is as a percentage
   */
  public int txbuf;
  /**
   * background noise level
   */
  public int noise;
  /**
   * remote background noise level
   */
  public int remnoise;

public String toString() {
return "MAVLINK_MSG_ID_RADIO : " +   "  rxerrors="+rxerrors+  "  fixed="+fixed+  "  rssi="+rssi+  "  remrssi="+remrssi+  "  txbuf="+txbuf+  "  noise="+noise+  "  remnoise="+remnoise;}
}
